### ISSUE TITLE
Client requested protocol TLSv1 is not enabled or supported in server context

### ISSUE THREAD

**Issue by Cuans** [zer0yu/Awesome-CobaltStrike#4]
Hello, I have a question, can you help me answer it? cobaltstrike 4.7.2 teamserver does not support TLSv1, causing win7 handshake failure, I use jdk11 and modified jdk.tls.disabledAlgorithms in java.security file but it doesn't work. how to solve this problem?

debug log：

javax.net.ssl|DEBUG|2D|HTTP session handler|2023-04-13 23:04:00.497 PDT|SSLExtensions.java:185|Ignore unavailable extension: supported_versions
javax.net.ssl|ERROR|2D|HTTP session handler|2023-04-13 23:04:00.498 PDT|TransportContext.java:363|Fatal (PROTOCOL_VERSION): Client requested protocol TLSv1 is not enabled or supported in server context (
"throwable" : {
  javax.net.ssl.SSLHandshakeException: Client requested protocol TLSv1 is not enabled or supported in server context
        at sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at sun.security.ssl.Alert.createSSLException(Alert.java:117)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:358)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:314)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:305)
        at sun.security.ssl.ClientHello$ClientHelloConsumer.negotiateProtocol(ClientHello.java:871)
        at sun.security.ssl.ClientHello$ClientHelloConsumer.onClientHello(ClientHello.java:823)
        at sun.security.ssl.ClientHello$ClientHelloConsumer.consume(ClientHello.java:801)
        at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
        at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
        at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
        at sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
        at sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:915)
        at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1006)
        at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:966)
        at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:294)
        at cloudstrike.NanoHTTPD$HTTPSession.readLine(NanoHTTPD.java:245)
        at cloudstrike.NanoHTTPD$HTTPSession.run(NanoHTTPD.java:265)
        at java.lang.Thread.run(Thread.java:833)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:597)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:194)}

)
javax.net.ssl|DEBUG|2D|HTTP session handler|2023-04-13 23:04:00.498 PDT|SSLSocketImpl.java:1749|close the underlying socket
javax.net.ssl|DEBUG|2D|HTTP session handler|2023-04-13 23:04:00.498 PDT|SSLSocketImpl.java:1775|close the SSL connection (passive)

**Comment by Cuans** [comment]
In addition, I use cobaltstrike 4.4, modifying jdk.tls.disabledAlgorithms can solve this problem, but it is invalid in version 4.7.2
